### ISSUE TITLE
Update documentation for password

### ISSUE THREAD

**Issue by Monduiz** [AndreaCirilloAC/updateR#13]
Shoudn't the documentation indicate this: 

 updateR(admin_password = "password") instead of :
 updateR(admin_password = \<password\>)?

**Comment by AndreaCirilloAC** [comment]
thank you for pointing this out, could you be more precise?
where do you see this token?

thanks

**Comment by Monduiz** [comment]
It is on the readme. I am not sure if this was intended. I think it is more informative if the syntax shown is the same from R.

**Comment by AndreaCirilloAC** [comment]
closed with https://github.com/AndreaCirilloAC/updateR/commit/0d08dfe5b3383d8d86f936842fceb3b329f224aa , substituting <PASSWORD> and clarifying its meaning anyway. 
thank you for pointing it out.
