### ISSUE TITLE
UpdateR fails to update but exits "smoothly"

### ISSUE THREAD

**Issue by sappelhoff** [AndreaCirilloAC/updateR#3]
Hi there, 

I am running R with the following:
- R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
- R Studio 1.0.136
- Mac OS 10.12.3

Trying to update R using `updateR()` leads to the following output:

    trying URL 'https://cran.rstudio.com/bin/macosx/R-3.3.2.pkg'
    Content type 'unknown' length 74323165 bytes (70.9 MB)
    ==================================================
    downloaded 70.9 MB

    R was updated to R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
    Everything went smoothly!

So in fact, it does not update at all.

I installed updateR on the 2nd Feb 2017 like this:

    library(devtools)
    install_github('andreacirilloac/updateR')

Any clue what the issue is? 

Thanks!
S.

**Comment by RobertMyles** [comment]
Hi,

If you restart R and run `version`, it should show the new version of R that has been installed.

**Comment by sappelhoff** [comment]
Hi Robert, 
thanks for the answer. That doesn't work (yet?) ... I see that your pull request has not yet been merged, so maybe that's why.

**Comment by AndreaCirilloAC** [comment]
As far as I can se the pull requests doesn't imply any other change than the ones to messages to the user. Am I right?

Andrea Cirillo
+39 3486881826
Via Meriggia 32
Settimo Milanese (MI), 
20019, Italy
it.linkedin.com/in/cirilloandrea
andreacirilloblog.wordpress.com

**Comment by sappelhoff** [comment]
@AndreaCirilloAC , you are right ... I just assumed there would be a connection, because @RobertMyles  referenced this issue to the fixes.

So as far as I tested the function this morning, the problem still persists.
