### ISSUE TITLE
Failure to Download

### ISSUE THREAD

**Issue by bholtdwyer** [AndreaCirilloAC/updateR#42]
I open R (4.0.4) on Mac OS 10.15.7, and try the following:

```
library(devtools)
devtools::install_github("AndreaCirilloAC/updateR")
```

I get back:
```
Downloading GitHub repo AndreaCirilloAC/updateR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/AndreaCirilloAC/updateR/tarball/HEAD' failed
```

**Comment by bholtdwyer** [comment]
Turns out was due to very slow download speeds due to VPN.

**Comment by HarveyXWu** [comment]
> Turns out was due to very slow download speeds due to VPN.

Hi there, I want to know how to use vpn to download this, should I do something in Rstudio? Or just open vpn and run the install command?

Thanks!
