### ISSUE TITLE
UpdateR extra parentheses

### ISSUE THREAD

**Issue by nsrath** [AndreaCirilloAC/updateR#6]
I tried to install UpdateR using devtools, but it produced the following error message

_Error in parse(outFile) : 
  /private/var/folders/__/78x6k4f55bx4qqpvy8jl05140000gn/T/Rtmp6FYqyz/devtools10871a88bae/AndreaCirilloAC-updateR-aac8add/R/upd:9:44: unexpected ')'
8:   if(is.null(admin_password)){
9:     stop("User system password is missing"))
                                              ^
ERROR: unable to collate and parse R files for package ‘updateR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/updateR’
Error: Command failed (1)_

It appears there is an extra close parenthesis at the end of line 9.

**Comment by AndreaCirilloAC** [comment]
thank you @nsrath . this got fixed by https://github.com/AndreaCirilloAC/updateR/commit/5f0501c312d779ec213c9c14d4911e0153694f54
